export const requiredFormField = [
  {
    id: 1,
    key: "name",
    label: "Field Name",
    type: "text",
    placeholder: "Enter field name",
    required: true,
  },
  {
    id: 2,
    key: "type",
    label: "Field Type",
    type: "select",
    required: true,
    options: [
      "Text",
      "Textarea",
      "Number",
      "Email",
      "Password",
      "Date",
      "Checkbox",
      "Radio",
      "Dropdown",
      "File",
    ],
  },
  {
    id: 3,
    key: "displayStatus",
    label: "Display Status",
    type: "switch",
    defaultValue: true,
  },
  {
    id: 4,
    key: "defaultValue",
    label: "Default Value",
    required: false,
    type: "text",
    placeholder: "Enter default value",
  },
  {
    id: 5,
    key: "required",
    label: "Required",
    type: "checkbox",
    defaultValue: false,
    required: false,
  },
//   {
//     id: 6,
//     key: "options",
//     label: "Options",
//     type: "textarea",
//     placeholder: "Enter options separated by commas",
//     showFor: ["Dropdown", "Radio", "Checkbox"],
//   },
];